# Generated by Django 4.2.7 on 2025-06-08 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslot',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='professional',
            field=models.ForeignKey(blank=True, help_text='Direct reference to professional user (for compatibility)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_availability_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unavailabledate',
            name='professional',
            field=models.ForeignKey(blank=True, help_text='Direct reference to professional user (for compatibility)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_unavailable_dates', to=settings.AUTH_USER_MODEL),
        ),
    ]
