# Generated by Django 4.2.7 on 2025-05-29 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alistpros_profiles', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='availabilityslot',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='unavailabledate',
            name='contractor',
        ),
        migrations.AddField(
            model_name='appointment',
            name='alistpro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='alistpro_appointments', to='alistpros_profiles.alisthomeproprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='alistpro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='alistpros_profiles.alisthomeproprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unavailabledate',
            name='alistpro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_dates', to='alistpros_profiles.alisthomeproprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='alistpros_profiles.servicecategory'),
        ),
    ]
