# Generated by Django 4.2.7 on 2025-05-30 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alistpros_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alisthomeproreview',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='alisthomeproreview',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of people who found this review helpful'),
        ),
        migrations.AddField(
            model_name='alisthomeproreview',
            name='professional_response',
            field=models.TextField(blank=True, help_text='Professional response to the review', null=True),
        ),
        migrations.AddField(
            model_name='alisthomeproreview',
            name='response_date',
            field=models.DateTimeField(blank=True, help_text='Date when professional responded', null=True),
        ),
        migrations.AddField(
            model_name='alisthomeproreview',
            name='service_category',
            field=models.ForeignKey(blank=True, help_text='Service category this review is for', null=True, on_delete=django.db.models.deletion.SET_NULL, to='alistpros_profiles.servicecategory'),
        ),
        migrations.AddField(
            model_name='alisthomeproreview',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='alisthomeproreview',
            unique_together={('alistpro', 'client')},
        ),
    ]
