# Generated by Django 4.2.7 on 2025-06-08 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alistpros_profiles', '0003_servicecategory_icon_timeoff_servicerequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alistpros_reviews_given', to=settings.AUTH_USER_MODEL),
        ),
    ]
