# Generated by Django 4.2.7 on 2025-06-08 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alistpros_profiles', '0004_fix_review_related_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_reviews_given', to=settings.AUTH_USER_MODEL),
        ),
    ]
