# Generated by Django 4.2.7 on 2025-06-08 20:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('alistpros_profiles', '0005_alter_review_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alisthomeproprofile',
            options={'ordering': ['-average_rating', '-total_jobs'], 'verbose_name': 'A-List Home Pro Profile', 'verbose_name_plural': 'A-List Home Pro Profiles'},
        ),
        migrations.AddField(
            model_name='alisthomeproprofile',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alistpro_address', to='core.address'),
        ),
        migrations.AddField(
            model_name='alisthomeproprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='alisthomeproprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Professional biography'),
        ),
        migrations.AddField(
            model_name='alisthomeproprofile',
            name='certifications',
            field=models.TextField(blank=True, help_text='Professional certifications'),
        ),
        migrations.AddField(
            model_name='alisthomeproprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='alistpro_covers/'),
        ),
        migrations.AddField(
            model_name='alisthomeproprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='alisthomeproprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alisthomeproprofile',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alisthomeproprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alisthomeproprofile',
            name='jobs_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alisthomeproprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='alisthomeproprofile',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alisthomeproprofile',
            name='license_type',
            field=models.CharField(blank=True, help_text='Type of license', max_length=100),
        ),
        migrations.AddField(
            model_name='alisthomeproprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='alisthomeproprofile',
            name='profession',
            field=models.CharField(blank=True, help_text='Primary profession/specialization', max_length=200),
        ),
        migrations.AddField(
            model_name='alisthomeproprofile',
            name='response_time_hours',
            field=models.PositiveIntegerField(default=24, help_text='Average response time in hours'),
        ),
        migrations.AddField(
            model_name='alisthomeproprofile',
            name='total_jobs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alisthomeproprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='alisthomeproprofile',
            name='business_description',
            field=models.TextField(blank=True, help_text='Professional biography'),
        ),
        migrations.AlterField(
            model_name='alisthomeproprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alisthomeproprofile',
            name='license_number',
            field=models.CharField(blank=True, help_text='Professional license number', max_length=100),
        ),
        migrations.AlterField(
            model_name='alisthomeproprofile',
            name='service_categories',
            field=models.ManyToManyField(blank=True, related_name='alistpros', to='alistpros_profiles.servicecategory'),
        ),
        migrations.AlterField(
            model_name='alisthomeproprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
