# Generated by Django 4.2.7 on 2025-06-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alistpros_profiles', '0006_upgrade_alistpro_profile_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='service_categories',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='review',
            name='client',
        ),
        migrations.RemoveField(
            model_name='review',
            name='job_assignment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='professional',
        ),
        migrations.RemoveField(
            model_name='timeoff',
            name='professional',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
