# Generated by Django 4.2.7 on 2025-06-08 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alistpros_profiles', '0007_remove_professionalprofile_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfessionalProfile',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='TimeOff',
        ),
    ]
