# Generated by Django 4.2.7 on 2025-06-26 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_message_message_type'),
        ('alistpros_profiles', '0008_delete_professionalprofile_delete_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicequote',
            name='first_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount for first payment (calculated automatically)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicequote',
            name='first_payment_percentage',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Percentage of total price for first payment', max_digits=5),
        ),
        migrations.AddField(
            model_name='servicequote',
            name='second_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount for second payment (calculated automatically)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicequote',
            name='supports_installments',
            field=models.BooleanField(default=True, help_text='Whether this quote supports installment payments'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='appointment_scheduled_at',
            field=models.DateTimeField(blank=True, help_text='When the appointment was scheduled', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='conversation',
            field=models.OneToOneField(blank=True, help_text='Associated conversation for this service request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request', to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='is_appointment_scheduled',
            field=models.BooleanField(default=False, help_text='Whether an appointment has been scheduled for this request'),
        ),
    ]
