# Generated by Django 4.2.7 on 2025-05-29 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alistpros_profiles', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AListHomeProStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('profile_views', models.IntegerField(default=0)),
                ('appointment_requests', models.IntegerField(default=0)),
                ('completed_appointments', models.IntegerField(default=0)),
                ('cancelled_appointments', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('alistpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='alistpros_profiles.alisthomeproprofile')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('alistpro', 'date')},
            },
        ),
        migrations.RenameField(
            model_name='dashboardstat',
            old_name='new_contractors',
            new_name='new_alistpros',
        ),
        migrations.RenameField(
            model_name='servicecategorystat',
            old_name='contractor_count',
            new_name='alistpro_count',
        ),
        migrations.AlterField(
            model_name='servicecategorystat',
            name='service_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='alistpros_profiles.servicecategory'),
        ),
        migrations.DeleteModel(
            name='ContractorStat',
        ),
    ]
