# Generated by Django 5.0.7 on 2025-04-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('MESSAGE', 'New Message'), ('APPOINTMENT', 'Appointment Update'), ('PAYMENT', 'Payment Update'), ('SYSTEM', 'System Notification'), ('MARKETING', 'Marketing'), ('REGISTRATION', 'User Registration'), ('PROFILE_UPDATE', 'Profile Update'), ('ALISTPRO_ONBOARDING', 'A-List Home Pro Onboarding'), ('ALISTPRO_VERIFICATION', 'A-List Home Pro Verification'), ('REVIEW', 'New Review')], max_length=25),
        ),
    ]
