# Generated by Django 4.2.7 on 2025-06-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_conversationmember_messagereaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('FILE', 'File'), ('LOCATION', 'Location'), ('SYSTEM', 'System Message'), ('QUOTE', 'Quote Message')], default='TEXT', max_length=20),
        ),
    ]
