# Generated by Django 4.2.7 on 2025-06-08 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alistpros_profiles', '0007_remove_professionalprofile_address_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to='alistpros_profiles.alisthomeproprofile'),
        ),
    ]
