# Generated by Django 4.2.7 on 2025-06-26 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alistpros_profiles', '0009_add_conversation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_alter_payment_professional'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment_type', models.CharField(choices=[('first', 'First Payment'), ('second', 'Second Payment')], max_length=10)),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Total amount paid by client', max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, help_text='Platform commission (5%)', max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Amount after platform fee', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Payment Received'), ('held', 'On Hold (14 days)'), ('released', 'Released to Professional'), ('refunded', 'Refunded to Client'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('hold_until', models.DateTimeField(blank=True, help_text='Date when payment will be automatically released (14 days after payment)', null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_payments_made', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_payments_received', to='alistpros_profiles.alisthomeproprofile')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='alistpros_profiles.servicequote')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('quote', 'installment_type')},
            },
        ),
    ]
