# Generated by Django 4.2.7 on 2025-06-26 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alistpros_profiles', '0009_add_conversation_fields'),
        ('payments', '0003_add_payment_installment_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escrowmilestone',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escrow_received', to='alistpros_profiles.alisthomeproprofile'),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='project_type',
            field=models.CharField(choices=[('simple', 'Simple Service'), ('installment', 'Installment'), ('complex', 'Complex Project')], default='simple', max_length=20),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='service_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_accounts', to='alistpros_profiles.servicequote'),
        ),
        migrations.AddField(
            model_name='escrowmilestone',
            name='hold_until',
            field=models.DateTimeField(blank=True, help_text='Date when payment will be automatically released (14 days after payment)', null=True),
        ),
        migrations.AddField(
            model_name='escrowmilestone',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount after platform fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='escrowmilestone',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes'),
        ),
        migrations.AddField(
            model_name='escrowmilestone',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrowmilestone',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform commission (5%)', max_digits=10),
        ),
        migrations.AddField(
            model_name='escrowmilestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Payment Received'), ('held', 'On Hold (14 days)'), ('completed', 'Work Completed'), ('approved', 'Approved by Client'), ('released', 'Released to Professional'), ('refunded', 'Refunded to Client'), ('disputed', 'Disputed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='escrowmilestone',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='escrowmilestone',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
