# Generated by Django 4.2.7 on 2025-06-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_escrowmilestone_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentinstallment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='paymentinstallment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='paymentinstallment',
            name='professional',
        ),
        migrations.RemoveField(
            model_name='paymentinstallment',
            name='quote',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentInstallment',
        ),
    ]
